base_link:
  sensor_kit_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0000
    pitch: 0.0000
    yaw: 0.0000
  velodyne_rear_base_link:
    x: 0.000
    y: 0.000
    z: 0.000
    roll: 0.000
    pitch: 0.000
    yaw: 0.000
  velodyne_front_base_link:
    x: 0.000
    y: 0.000
    z: 0.000
    roll: 0.000
    pitch: 0.000
    yaw: 0.000
